# Generated by Django 5.2.8 on 2025-11-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cotizacion_fecha_vencimiento_cotizacion_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='afp_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='salud_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sueldo_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
