# Generated by Django 5.2.8 on 2025-11-14 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_empleado_user'),
        ('ventas', '0003_cotizacion_afp_descuento_cotizacion_salud_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_nomina', to='rrhh.empleado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
        ),
    ]
