# Generated by Django 5.2.8 on 2025-11-14 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_empleado_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacaciones',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='comentario_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
