# Generated by Django 5.2.8 on 2025-11-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_solicitudrecuperacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecuperacion',
            name='nueva_password',
        ),
    ]
