# Generated by Django 5.2.7 on 2025-12-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
