# Generated by Django 5.2.7 on 2025-12-30 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['producto__nombre']},
        ),
        migrations.AddField(
            model_name='stock',
            name='estado',
            field=models.CharField(choices=[('apto', 'Apto para venta'), ('defectuoso', 'Defectuoso'), ('cuarentena', 'En cuarentena'), ('reclamo', 'En reclamo a proveedor'), ('dado_baja', 'Dado de baja')], default='apto', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='fecha_defecto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='motivo_defecto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='usuario_reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('agregar', 'Agregar'), ('restar', 'Restar'), ('venta', 'Venta'), ('producto_creado', 'Producto Creado'), ('producto_eliminado', 'Producto Eliminado'), ('cambio_estado', 'Cambio de estado'), ('reclamo_proveedor', 'Reclamo a proveedor'), ('dado_baja', 'Dado de baja')], max_length=30),
        ),
    ]
