# Generated by Django 5.2.7 on 2025-12-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_stock_options_stock_estado_stock_fecha_defecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('agregar', 'Agregar'), ('restar', 'Restar'), ('venta', 'Venta'), ('producto_creado', 'Producto Creado'), ('producto_eliminado', 'Producto Eliminado'), ('cambio_estado', 'Cambio de estado'), ('reclamo_proveedor', 'Reclamo a proveedor'), ('dado_baja', 'Dado de baja'), ('devolucion', 'Devolución recibida')], max_length=30),
        ),
    ]
