# Generated by Django 5.2.7 on 2025-12-30 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_movimientostock_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('es_principal', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.producto')),
            ],
            options={
                'ordering': ['-es_principal', '-creado'],
            },
        ),
    ]
