# Generated by Django 5.2.8 on 2025-11-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompraInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta')], max_length=10)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('CLP', 'Peso Chileno'), ('ARS', 'Peso Argentino'), ('BRL', 'Real Brasileño')], default='USD', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, help_text='Tipo de cambio a moneda local', max_digits=10)),
                ('monto_neto', models.DecimalField(decimal_places=2, help_text='Monto sin IVA', max_digits=12)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA', max_digits=5)),
                ('monto_iva', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('monto_total_local', models.DecimalField(decimal_places=2, editable=False, help_text='Total en moneda local', max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_internacionales', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Documento de Compra Internacional',
                'verbose_name_plural': 'Documentos de Compra Internacional',
                'ordering': ['-fecha'],
            },
        ),
    ]
